title: 'DeepPose'

seed: 42
use_deterministic: False
gpus: 0, 1, 2, 3
num_workers: 4
saveDir: 'resnet50'

model:
  name: 'DeepPose'
  backbone: 'resnet50'
  nkpts: 17
  checkpoint: 
  pretrained: True

train:
  batch_size: 32
  num_epochs: 100
  mini_batch_count: 1
  optimizer: 'RMSprop'
  shuffle: True
  lr: 2.5e-4
  lr_step: 30
  lr_gamma: 0.1
  momentum: 0.9
  weight_decay: 5e-4
  save_freq: 10
  dropLR: 5
  dropMag: 0.7
  
valid:
  val_interval: 1
  save_interval: 10



data:
  name: 'MPII'
  data_dir: './data/MPII/images'
  train_split: 'train'
  val_split: 'valid'
  

